# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SchedulingApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SchedulingApp

  target 'SchedulingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SchedulingAppUITests' do
    # Pods for testing
  end

pod 'FSCalendar'

end
